### ISSUE TITLE
Token image url is dropped (temporarily?) when connected to a D&D 5e sheet

### ISSUE THREAD

**Issue by codyshepherd** [beyondtabletop/beyondtabletop#1]
Steps to reproduce:

* Add a D&D 5e sheet to your dashboard
* In a battlemap, add a token
* Add a working image url to the token
* Add the token to combat
* In the bottom pop-up menu, connect the token to a sheet, select the sheet, then hit Connect
* Notice that the image-url has been cleared, the image representing the token has been replaced with the default letter style

Sometimes the image and its url comes back, though it's unclear what causes this.

**Comment by cranderveldt** [comment]
What's happening is the image associated with your character sheet is replacing the one associated with the token. If you want it to stick, put that working image url on your character sheet under Profile Image on the General tab. You're right that a blank image shouldn't overwrite a working one though, I'll make that fix.
