### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xmclark** [beyondtabletop/beyondtabletop#5]
I don't see a license in this repo. What is the license?

**Comment by cranderveldt** [comment]
I don't really know anything about Licenses. I asked around and haven't found a satisfactory answer. Basically I want to pick one where people can use the code as long as the products they make from the code are also open source, and not for-profit. So whichever one that is, that's what should be in this repo 😅

**Comment by xmclark** [comment]
Would MIT meet your needs?

https://choosealicense.com/licenses/mit/

**Comment by cranderveldt** [comment]
I talked it over with some friends and ended up going with [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/). Thanks for bringing this up!
